name: Debian image - aarch64

on: [push]

jobs:
  build-custom-image-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: prepare
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y wget ca-certificates && wget https://fai-project.org/download/fai-project.gpg && sudo cp fai-project.gpg /etc/apt/trusted.gpg.d/ && echo "deb https://fai-project.org/download bookworm koeln" | sudo tee -a /etc/apt/sources.list
    - name: install deps
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ca-certificates debsums dosfstools fai-server fai-setup-storage fdisk make python3 python3-libcloud python3-marshmallow python3-pytest python3-yaml qemu-utils udev
    - name: FAI setup
      run: sudo fai-setup
    - name: build the image
      run: sudo fai-diskimage --verbose --size 2G --class BASE,DEBIAN,CLOUD,ARM64,BOOKWORM,BUILD_IMAGE,SYSTEM_BOOT --cspace DIR/config_space/bookworm arm64.raw
    - name: Publish the artifiacts
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # aka v4.0.0
      with:
        name: image
        path: arm64.raw
